[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = "Site built with <a href=\"https://gohugo.io/\" class=\"gdoc-footer__link\" target=\"_blank\">Hugo</a> and <a class=\"gdoc-footer__link\" href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>. Project developed and maintained with ❤️ by <a href=\"https://www.linkedin.com/in/yvand/\" class=\"gdoc-footer__link\" target=\"_blank\">Yvan Duhamel</a>."
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/new-release-v28.0/">EntraCP v28, released on December 2, 2024, contains an important security update</a>'
    navBarButtonText = "Get started"
